### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Alispezzate** [xClaudi0/xClaudi0.github.io#1]
When I open the website my CPU usage spikes up to 99%
I would suggest disabling some javascript useless functions since the website is supposed to be browsed from people with any kind of system and considering that my pc is not that bad there's someone who's gonna have a much worse experience. My 2 cents.

**Comment by xClaudi0** [comment]
Kitemmuort

**Comment by zAlweNy26** [comment]
> When I open the website my CPU usage spikes up to 99%
> I would suggest disabling some javascript useless functions since the website is supposed to be browsed from people with any kind of system and considering that my pc is not that bad there's someone who's gonna have a much worse experience. My 2 cents.

I agree with you. I also noticed an increase in CPU usage. I suggest closing the site for the good of all.

**Comment by Alispezzate** [comment]
You see? That's what I meant, thanks for supporting my idea.

**Comment by xClaudi0** [comment]
`<h1> SUCA </h1>`

**Comment by Alispezzate** [comment]
# This is an <h1> tag
